### ISSUE TITLE
Confirm Booking

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Vita-App/Vita#11]
Once a mentor chooses a mentor picks a time slot, and enters relevant data, the backend should send information to the mentor, and once the mentor accepts the booking, a vita meet link needs to be created and add to the Booking Collection.

<img width="343" alt="image" src="https://user-images.githubusercontent.com/54576074/145155084-60191037-5ac5-451c-8423-a6cb65b53fa8.png">

https://github1s.com/Rishabh-malhotraa/vita/blob/HEAD/api/src/Models/Booking.ts#L3-L19

In the backend, while validating the vita-meet link, we need to check Node Cache and MongoDB Booking collection too then 

**the tentative flow goes along the following lines**

1. when mentee selects date time for a mentor and presses confirm the booking 
2. we send that information to the backend using a POST request
3.  backend saves that information in booking collection MongoDB
4. The mentor is notified when he visits the website(maybe we can send him a mail too) that some person wants to get mentorship from him
5. the mentor can now accept/reject/propose a different time
6. Once the mentor accepts we would generate a meet link (Vita meet, or use google api to generate a Gmeet link) and email the link to the mentor
7. We need to setup an SMTP server with the right configurations so the mail we send doesn't go straight to spam!

**Comment by hazemessam** [comment]
I'm interesting to work on it under GSSoC

**Comment by amir-ammar** [comment]
i'm a gssoc '22 participant and would like to work on this issue

**Comment by himanshusanecha** [comment]
I am interested to work upon this issue.

**Comment by Rishabh-malhotraa** [comment]
This will be worked on once the login flow is completed.

**Comment by Shelly011s** [comment]
Assign this to me once the login flow is complete.

**Comment by mayank-del** [comment]
@Rishabh-malhotraa , can work under this issue under gssoc22
