### ISSUE TITLE
Styling Email Templates

### ISSUE THREAD

**Issue by Lalit3716** [Vita-App/Vita#124]
### Description

Research on how to style our email templates using node-mailer. Currently we are just sending a plain email message like this:-

![Screenshot 2022-07-05 004949](https://user-images.githubusercontent.com/84276404/177208334-2818dcb0-da0b-4cb7-b46d-2a6731bf5260.png)

We want to send something like this:-
![Screenshot 2022-07-05 004916](https://user-images.githubusercontent.com/84276404/177208403-8b990f52-3998-4a04-af8c-c303780fabc2.png)

### Domain

Backend Dev (Express)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by ancoreraj** [comment]
@Lalit3716 I want to work on this. Can you assign it to me.
