### ISSUE TITLE
Write Unit Test for end-points

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Vita-App/Vita#13]
Write unit test to validate all our endpoints from the backend, (use a testing MongoDB database to do that), and then write a Github actions workflow to run all those tests before making any changes!

**Comment by manav-06** [comment]
@Rishabh-malhotraa can you assign this to me?

**Comment by Rishabh-malhotraa** [comment]
How do you plan to implement testing(I want to know your approach)? Plus, what library are you thinking of using?

**Comment by Lalit3716** [comment]
Hello, I tried setting up testing on backend using mocha for running tests, chai for assertions and supertest libraries.

**Comment by Lalit3716** [comment]
So if no one is working on this maybe you can assign this to me ? and I will open a PR for the same for code review ?

**Comment by Rishabh-malhotraa** [comment]
Sure, remember with testing, adding test cases are more important than the test itself

**Comment by Lalit3716** [comment]
Great! I will start writing good test cases once you approve the pattern I followed for setting up testing.
