### ISSUE TITLE
[logo]: vlang stole your logo!

### ISSUE THREAD

**Issue by l1mey112** [Vita-App/Vita#148]
### Description

The V programming language and all of it's source material use your logo!

It's website is [here](https://vlang.io/), it has your logo plastered all over the front page. I consider messaging them for negotiation. 

Report back to me and I'll give them piece of my mind for stealing your logo.

### Domain

Full Stack

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by ylluminate** [comment]
Thanks for reporting this @l1mey112 to the Vita community. Hopefully they'll resolve this very quickly since this is an ugly stain on their project that may be perhaps a little flattering to the (awesome) V programming language.

**Comment by ArtemkaKun** [comment]
What a thing! Shame for the Vlang community

**Comment by Rishabh-malhotraa** [comment]
@ylluminate  @ArtemkaKun @l1mey112 Hey I just searched for 'V' icon on google and took the first image i liked, there was no ill-intention to steal the logo or anything, we will change it to something else soon. Thanks for letting us know!

**Comment by ArtemkaKun** [comment]
Thanks :)
