### ISSUE TITLE
[UI]: Improve the notifications component

### ISSUE THREAD

**Issue by Lalit3716** [Vita-App/Vita#151]
### Description

We currently have this notifications component:

![Screenshot 2022-09-24 225151](https://user-images.githubusercontent.com/84276404/192110869-6d86c381-24c9-47d8-a97e-ad9c01237963.png)

We can make it look good by making it something like this:

![](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F312c3b95-5dcb-4c69-8d9c-065bdbbd24f6%2FUntitled.png?table=block&id=e015b313-332c-41a3-b992-0c127e7ae50a&spaceId=26c7303e-f8b5-47c1-9d4f-c2a99f1890a9&width=2000&userId=5190b022-4af9-4190-bb00-7a4709a13979&cache=v2)

### Domain

Front-End (Styling/Markup)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by AyushK-101** [comment]
@Lalit3716 I was unassigned from the issue, might be because I self-assigned it (a few days) before the Semester long/ Hacktober period. The issue has the Assigned tag but no one has been assigned. So can I work on it?

**Comment by Lalit3716** [comment]
Hi @AyushK-101, any updates on this one?

**Comment by Sauvikn98** [comment]
Interested @Lalit3716
