### ISSUE TITLE
[UI]: Create a 404 Page

### ISSUE THREAD

**Issue by Lalit3716** [Vita-App/Vita#155]
### Description

Currently, we don't have any 404 page for our website.

- Design a dark-themed 404 page.
- Make a wildcard route to catch all other routes to display that page.

### Domain

Front-End (Styling/Markup)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Volley-Freak** [comment]
Hii Lalit. Would be happy to create this page.
Please assign this task to me.

**Comment by SOUMYADIP76** [comment]
i would like to solve this issue. Please assign me this is issue @Lalit3716

**Comment by sarkartanmay393** [comment]
I would love to work on it.
- From JWOC

**Comment by sarkartanmay393** [comment]
I would love to work on it.
- From JWOC

**Comment by sarkartanmay393** [comment]
@Lalit3716 When will you start assigning?

**Comment by sarkartanmay393** [comment]
@Lalit3716 When will you start assigning?

**Comment by sandeeprawat28** [comment]
Please assign this issue to me

**Comment by Lalit3716** [comment]
Hi guys it's awesome to see you all interested in this issue but as the guidelines I will have to assign the one who commented first 😅, if he/she fails to complete task in 2-3 days I will assign to next person! Till then search for bugs on the website and raise issues!
