### ISSUE TITLE
[Testing]: Configure Vitest for setting up testing in this project.

### ISSUE THREAD

**Issue by Lalit3716** [Vita-App/Vita#165]
### Description

Right now we don't have any unit testing going for the project. I want to set up Vitest to start writing some unit tests.
 
 Learn about Vitest here: https://vitest.dev/guide/
 Guide: https://eternaldev.com/blog/testing-a-react-application-with-vitest/

### Domain

Full Stack

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by sarkartanmay393** [comment]
I am giving it a try under JWOC
