### ISSUE TITLE
Enable Time Conversion in DatePicker

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Vita-App/Vita#18]
Convert the mentor's scheduled time slot to locale time: 

to do this, we also have to change the way we store `avalilable_timeslot` information in the backend

**Before working on this, please explain your thought process! on how do you plan to restructure to `available_timeslots` collections**

![image](https://user-images.githubusercontent.com/54576074/145520322-b880962e-84bb-4617-b8ed-b0e3e7ee4f3a.png)

<img width="470" alt="image" src="https://user-images.githubusercontent.com/54576074/145520652-e1970b1a-cf3c-41be-9d1a-baf79ccf465a.png">

https://mui.com/components/autocomplete/#githubs-picker

**Comment by hazemessam** [comment]
Is it a frontend task?

**Comment by hazemessam** [comment]
Is it a frontend task?
the time that is stored in the database should be the mentor's local time and when frontend fetch it should convert it according to mentee selected local time

**Comment by Rishabh-malhotraa** [comment]
This is in backlog right now, first we need to fix #12 first

**Comment by hazemessam** [comment]
> This is in backlog right now, first we need to fix #12 first

Ok, #12 looks interesting to me. Please add GSSoC'22 label to it and assigned it to me
