### ISSUE TITLE
Make Backend Serverless

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Vita-App/Vita#19]
Restructure Backend from Heroku to serverless architecture (better for long-term scalability).

- Before going any further, research on which provider to use and why? (AWS, Azure, GCP)
- Research on how you would maintain sessions.
- Research on how to use serverless when developing locally.
- Rate limit end-points, to prevent DDoS attacks.

---

**Comment by mayank-del** [comment]
Can i work under this issue under gssoc22
