### ISSUE TITLE
Add theme switcher

### ISSUE THREAD

**Issue by adarsharyan002** [Vita-App/Vita#43]
I would like to add a theme switch button at the top, a light theme will be good for the website

**Comment by Rishabh-malhotraa** [comment]
How to do you plan to implement theme switching, just so that we are on the same page about it.

**Comment by adarsharyan002** [comment]
I will use localstorage to keep track of the property instead of using localState, and use simple css for the background and font-color

**Comment by Rishabh-malhotraa** [comment]
Right, you also would have to do a lot of refactoring in codebase.
