### ISSUE TITLE
Create Blog site for Vita 

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Vita-App/Vita#62]
### Description

We would not add anything to the client folder for this but create a new subdir called blog

This would be hosted on a different subdomain like `blog.vita.com`

Example : https://blog.adplist.org/

- Discussion on which headless CMS to use & why (Gatsby, Ghost, Strapi, Netlify, WordPress, etc)
- It should be cheap (ideally free)
- I should be easily integrated with React
- Adding blogs should be as easily as this would be managed by non-technical people

### Domain

Front-End (Styling/Markup)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE%20OF%20CONDUCT.md) of this project.

**Comment by nitishsaini706** [comment]
@Rishabh-malhotraa Can i use typescript or next.js for this blog site ?

**Comment by Rishabh-malhotraa** [comment]
> @Rishabh-malhotraa Can i use typescript or next.js for this blog site ?
> 

I think with blogging websites `Sever side generated pages` do not make sense, a static page generator like gatsby would me more recommend.

But you can let me know how do you plan to implement this with Next.js

Plus I assume you would also be using a cms with next.js

**Comment by nitishsaini706** [comment]
@Rishabh-malhotraa Can we connect on discord

**Comment by Senor-Ducky** [comment]
If Next.js is being used I would like to work along with @nitishsaini706  on this task, please assign me to this, also if you need to get in touch with me here's my discord tag Senor-Ducky#2521
