### ISSUE TITLE
Issue regarding ui of booking slots

### ISSUE THREAD

**Issue by Sayan-dev** [Vita-App/Vita#63]
### Description

**While Booking a slot with a mentor, The UI is not consistent for the date and time selection when I come back from the email, agenda input screen.** 
### 
This Happens after I fill the agenda and come back to change the scheduled date
![but-vita1](https://user-images.githubusercontent.com/42710260/157383370-793fd633-dc11-4fed-9a18-953f252d0389.png)
![bug-vita2](https://user-images.githubusercontent.com/42710260/157383540-370f05dc-dfdb-4b0b-a9c5-fc4fdbdab723.png)
 But If the fields are empty, then going back the **UI** is perfect

### Domain

Front-End (Styling/Markup)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Rishabh-malhotraa** [comment]
I think this is a screen-width issue, we need to fix the some CSS properties to take care of responsiveness for smaller screens


It works fine on my screen
<img width="904" alt="image" src="https://user-images.githubusercontent.com/54576074/157523976-3f391752-aa90-4769-afc8-fb79dc067d36.png">

**Comment by jyotivakare33** [comment]
@Rishabh-malhotraa Please assignt this issue to me under GSSOC'22
