### ISSUE TITLE
Make Figma Mockups of the webstie

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Vita-App/Vita#67]
### Description

Make Figma mockups of the entire website

- you **don't need to design anything on your own**. Just replicate the current design of the website on Figma.

### Domain

UI/UX

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by jyotivakare33** [comment]
Hi @Rishabh-malhotraa can you assign this issue to me under Gssoc22

**Comment by Rishabh-malhotraa** [comment]
Do you have experience with figma?

**Comment by jyotivakare33** [comment]
No @Rishabh-malhotraa Apologies my bad i assumed it to different issue.

**Comment by masterpranay1** [comment]
Hey @Rishabh-malhotraa  I would like to work on the Figma Design for Vita. 
I have previous experience with figma. These are my some of the work on figma
- https://www.figma.com/file/fUXAI9ipGeknQrIPXukh3M/Snake-Game-UI?node-id=0%3A1
- https://www.figma.com/file/DNQCGyy4F9IMBqDDK3jkIn/Smart-form?node-id=0%3A1

I am always excited about UI / UX . Please assign this issue to me.

**Comment by Rishabh-malhotraa** [comment]
Why don't you start by creating the mockups for the [sign-up pages](https://deploy-preview-64--vitaa-app.netlify.app/complete-signup)? We mainly need the mockups to improve the colour theme and make a light theme. It is way faster to do all of that on Figma than by testing things manually by changing CSS

**Comment by masterpranay1** [comment]
Sure!! I will start with sign up / sign in page

**Comment by Sukriti-m** [comment]
Hi @Rishabh-malhotraa 
If @masterpranay1 is delaying this task, then I'd be grateful if you could assign this task to me under GSSOC'22.
I have experience in UX/UI design and know my way around Figma.

The following are the links to my Figma design: 

- https://www.figma.com/file/Fci0j9SBxtqLcEjJw3qxEX/Sukriti-Maurya_STATIONERY-WEBSITE
- https://www.figma.com/file/w7xUpMsN3j2te8e3LemjkW/1-Game-Library

**Comment by dasgupta002** [comment]
Has anyone done with this issue?
Else I am interested in solving this one @Rishabh-malhotraa .
