### ISSUE TITLE
No copy link option avalaible 

### ISSUE THREAD

**Issue by yahya-cloud** [Vita-App/Vita#68]
### Description

As of now the user have to copy the link by selecting the whole room link, no click to copy option present.

![Screenshot 2022-03-18 at 13-33-02 Meeting by yahya](https://user-images.githubusercontent.com/59670962/158960723-75fb971a-c33b-45d2-b56f-ee03a4d0234c.png)

### Domain

Front-End (Styling/Markup)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by yahya-cloud** [comment]
Hello, can you please assign me this issue.

**Comment by jyotivakare33** [comment]
@Rishabh-malhotraa Can you assign me this issue under GSSOC'22
