### ISSUE TITLE
Add an Admin Panel

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Vita-App/Vita#7]
Add an Admin Panel to monitor all scheduled meeting meetings, and if there was a no-show; time out that person's account and send him/her a message asking for an explanation. 

Before Working on this. Let me know how you plan to solve this, by explaining your thought process.

You can use a template admin panel like (I feel this can add a lot of bloat)
https://berrydashboard.io/free/

**_(Or you can create one from scratch using mui-5 component library. The dashboard must be responsive)_**
## Example of custom dashboard

![image](https://user-images.githubusercontent.com/54576074/145152262-5294df30-a3ca-4480-8bb3-53cf2ea36ab7.png)

![image](https://user-images.githubusercontent.com/54576074/145152152-f687ea61-645f-4b74-8ed2-ee693663533d.png)

![image](https://user-images.githubusercontent.com/54576074/145152373-c407233e-a86a-4fe6-95d8-ed4e115ebbe8.png)

https://user-images.githubusercontent.com/54576074/145151875-93107a8c-a08c-43f1-8bd4-4951ea8284d8.mp4

**Comment by Rishabh-malhotraa** [comment]
The admin panel would be a different site on another subdomain.

- The admin should have two factored authentication.

I’m thinking of using any pre-existing admin panels library for React, but they usually provide many features but restrict customizability.

- Approve a mentor account
- **Ability to time-out ban or terminate any account.**
- Look at all the past — ongoing — upcoming mentorship sessions.
- Resolve queries. (I’m thinking of using a third party chatbot like intercomn to do the following)
- Ability to send email to all the signed up mentors-mentee

## Good templates

https://material-ui.com/store/previews/minimal-dashboard-free/
https://material-ui.com/store/previews/soft-ui-pro-dashboard/

**Comment by Sahaj-Srivastava24** [comment]
Hey @sulogna2001
Would you like to elaborate your ideas regarding no show mentors?

**Comment by Lalit3716** [comment]
Is anyone working on this or is it in development ?
I would love to tackle this issue.
