### ISSUE TITLE
Mentor Profile Card UI Improvement

### ISSUE THREAD

**Issue by 19arnab190201** [Vita-App/Vita#83]
### Description

I want to improve the profile card UI for better look and feel keeping in mind the design pattern of the project please assign it to me  under the tag GSSOC22

### Domain

Front-End (Styling/Markup)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Rishabh-malhotraa** [comment]
How do you plan to improve the design?
