### ISSUE TITLE
Enable user to call the FTS endpoint

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Vita-App/Vita#87]
### Description

Currently, the text field is disabled, we should enable it to allow users to search-text input text.
- The [API to do an FTS query](https://github.com/Rishabh-malhotraa/Vita/blob/main/api/src/controllers/api-controller.ts#L8-L53) on the Mentor Collection is already been implemented, we need to integrate it with the frontend
- Add Debouncing when the user is entering text in the input field. [Learn more about Debouncing](https://www.youtube.com/watch?v=cjIswDCKgu0)
<img width="1085" alt="Screenshot 2022-04-17 at 4 16 22 PM" src="https://user-images.githubusercontent.com/54576074/163711231-e1cae71b-3d82-41e2-9844-d33968497184.png">

Bonus : 
- Sanitize the user input before making the search query. [Pkg: mongo-express-sanitize](https://www.npmjs.com/package/express-mongo-sanitize)

### Domain

Front-End (State-Management React)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Sahaj-Srivastava24** [comment]
I wanna work on this. I heard the API endpoint is set, and all that is left is debouncing the input field. 
Can I get assigned to this..?
