### ISSUE TITLE
Contributor Component on the Landing Page

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Vita-App/Vita#99]
### Description

Create a contributor component at the bottom of the landing page to celebrate open source contributions from all the contributors and give them a shoutout. 

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/54576074/165600690-6307fff3-f6c0-456f-857d-e2fd35e5a3af.png">

https://iiitdplaybook.web.app/homepage  (Scroll to the bottom)

- Use the chip components from mui

### Domain

Front-End (Styling/Markup)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by navyasharma0203** [comment]
Does this issue come under GSSOC'22...If yes, could you please assign a level tag for it?? Thanks :)
